artifacts_root: artifacts  # Root directory for all artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing  # Source URL
  local_data_file: artifacts/data_ingestion/data.zip  # Local file path
  unzip_dir: artifacts/data_ingestion  # Extraction directory

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5  # Base model file path
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5  # Updated model path

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5  # Trained model file path